### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by farribeiro** [flathub/br.gov.fazenda.receita.irpf2023#24]
Hello 

The new IRPF2024 v1.0 will be released tomorrow

Please consider pack the new app.

Best regards,
Fábio

**Comment by guihkx** [comment]
I do plan to, but I don't think it's publicly ready yet?

If it is, can you please share the download link?

**Comment by farribeiro** [comment]
https://www.gov.br/receitafederal/pt-br/centrais-de-conteudo/download/pgd/dirpf

Lets take a look closer.

**Comment by guihkx** [comment]
Sure, but where's the 2024 edition?

![image](https://github.com/flathub/br.gov.fazenda.receita.irpf2023/assets/626206/f00cc6ef-8669-42e6-bfb6-5824d7404b11)

**Comment by farribeiro** [comment]
Tomorrow... https://valorinveste.globo.com/imposto-de-renda-2024/noticia/2024/03/11/receita-federal-libera-programa-da-declaracao-do-imposto-de-renda-2024-nesta-terca-feira-12-veja-como-baixar.ghtml

**Comment by farribeiro** [comment]
Good morning.

Take a look now

**Comment by guihkx** [comment]
Sent it for review on Flathub: https://github.com/flathub/flathub/pull/5044

This is probably a really bad timing, though, because I think the only person who can merge pull requests there is on vacation, and probably will be for entirety of March. And so I don't know if he'll look at my submission until his vacation ends...

In any case, I'll close this.
